version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.0
    container_name: keycloak
    command: start-dev --import-realm
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://host.docker.internal:5432/keycloak
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 10091
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
    ports:
      - "10091:10091"
    volumes:
      - ./config/keycloak/keycloak-realm-all.json:/opt/keycloak/data/import/realm.json
    extra_hosts:
      - "host.docker.internal:host-gateway"

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
